// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlLV4g3rSDRl7SEJYix-rAYLfkDC4Zruw',
    appId: '1:973741690796:web:4cdf4d610b77363c6b3409',
    messagingSenderId: '973741690796',
    projectId: 'ulearning-flutter',
    authDomain: 'ulearning-flutter.firebaseapp.com',
    storageBucket: 'ulearning-flutter.appspot.com',
    measurementId: 'G-1FN6ZFS1CX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaFF-is-6oGf16e2Pj4LBMNYc56zbHwwA',
    appId: '1:973741690796:android:3589c9630dd1decb6b3409',
    messagingSenderId: '973741690796',
    projectId: 'ulearning-flutter',
    storageBucket: 'ulearning-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdJbitFTuok0E34KGCHQSHi_0-9TnS0Tw',
    appId: '1:973741690796:ios:eb6608d12c0d8e486b3409',
    messagingSenderId: '973741690796',
    projectId: 'ulearning-flutter',
    storageBucket: 'ulearning-flutter.appspot.com',
    iosBundleId: 'com.agprastyo.ulearningApp',
  );
}
